Don't use /public path for custom functions with shared runtime
OfficeDev/Excel-Custom-Functions pull request #393
Opened 2024-01-25 22:57 UTC by akrantz

This fixes the manifest so the custom functions metadata (functions.json) and code (functions.js) come directly from the root. It should not try to load from /public.

1. **Do these changes impact any *npm scripts* commands (in package.json)?** (e.g., running 'npm run start')
No

2. **Do these changes impact *VS Code debugging* options (launch.json)?**
No

3. **Do these changes impact *template output*?** (e.g., add/remove file, update file location, update file contents)
No

4. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
No

Describe manual testing done.

1. Open VS Code.
2. Start Dev-Server task using Terminal, Run task...
3. Verified in browser that https://localhost:3000/functions.json serves up metadata correctly. Likewise for functions.js and taskpane.html.
4. Set a breakpoint in functions.ts on add() function.
5. Launch Excel Desktop for debugging. 
6. Type "=CONTOSO.ADD(1, 2)" in a cell.
7. Hit the breakpoint in functions.ts.  Press play button to continue.
8. See that the custom function returned 3 which is shown in the cell.

2024-01-25 23:45 UTC, millerds requested changes
Shouldn't we change the webpack config files to not have the public path anymore (they are only there to support functions)?

2024-01-25 23:45 UTC, millerds commented on .hintrc
> +}
This doesn't look like it applies to the public path

2024-01-25 23:45 UTC, millerds commented on null
> +Error:  Access is denied.
What's this for?

2024-01-25 23:47 UTC, millerds commented
Just saw the update . . . sorry about the extra comments.   Still think the webpack config files should be updated.

2024-01-26 03:56 UTC, akrantz commented
Is your question whether to delete the `publicPath: "/public",` in the devServer part of webpack config?

```
    devServer: {
      static: {
        directory: path.join(__dirname, "dist"),
        publicPath: "/public",
      },
```

I can delete it, although I don't think it makes a difference really.

2024-01-26 18:02 UTC, akrantz commented
I pushed a commit that removes devServer.static.

2024-01-26 18:08 UTC, millerds commented
Thanks.  What about the test manifest and webpack config?  We should make sure it test the same way it's used.

2024-01-26 19:03 UTC, akrantz commented
Updated.

2024-01-26 19:06 UTC, merged